---
name: ubuntu

on:
  - push

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.15.4-otp-26'
        otp-version: '26.0.2'
        fetch-depth: 0
